[profile.default]
src = "contracts"
out = "out"
libs = ["node_modules","lib"]
test = "contracts/tests"
cache_path = "forge-cache"
solc = "0.8.23"
optimizer = true
optimizer_runs = 2
evm_version ="shanghai"
[invariant]
fail_on_revert = true
eth-rpc-url = "https://mainnet.infura.io/v3/121c74e81cc249fb82a35814aeae26d7"
[rpc_endpoints]
mainnet = "https://mainnet.infura.io/v3/121c74e81cc249fb82a35814aeae26d7"
polygon = "https://polygon-rpc.com"


# See more config options https://github.com/foundry-rs/foundry/tree/master/config
